// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
try {
  require("dotenv/config");
} catch (e) {
  // Ignore in production environments
}
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "npx tsx prisma/seed.ts",
  },
  datasource: {
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
    shadowDatabaseUrl: process.env["SHADOW_DATABASE_URL"],
  },
});
