export const BEPS_REASON_CODES = {
  bepsNotApplicable: "BEPS_NOT_APPLICABLE",
  unsupportedCycle: "UNSUPPORTED_CYCLE",
  buildingInScope: "BUILDING_IN_SCOPE",
  notApplicableUnderSizeThreshold: "NOT_APPLICABLE_UNDER_SIZE_THRESHOLD",
  notApplicableRecentConstruction: "NOT_APPLICABLE_RECENT_CONSTRUCTION",
  notApplicableUnsupportedPropertyType: "NOT_APPLICABLE_UNSUPPORTED_PROPERTY_TYPE",
  supportedPathwaysIdentified: "SUPPORTED_PATHWAYS_IDENTIFIED",
  alreadyCompliantByScore: "ALREADY_COMPLIANT_BY_SCORE",
  missingBaselineInput: "MISSING_BASELINE_INPUT",
  missingEvaluationInput: "MISSING_EVALUATION_INPUT",
  missingCurrentScoreForRouting: "MISSING_CURRENT_SCORE_FOR_ROUTING",
  performancePathwayEligible: "PERFORMANCE_PATHWAY_ELIGIBLE",
  performancePathwayIneligible: "PERFORMANCE_PATHWAY_INELIGIBLE",
  standardTargetPathwayEligible: "STANDARD_TARGET_PATHWAY_ELIGIBLE",
  standardTargetPathwayIneligible: "STANDARD_TARGET_PATHWAY_INELIGIBLE",
  prescriptivePathwayEligible: "PRESCRIPTIVE_PATHWAY_ELIGIBLE",
  trajectoryPathwayEligible: "TRAJECTORY_PATHWAY_ELIGIBLE",
  trajectoryPathwayIneligible: "TRAJECTORY_PATHWAY_INELIGIBLE",
  missingBaselineAdjustedSiteEui: "MISSING_BASELINE_ADJUSTED_SITE_EUI",
  missingCurrentAdjustedSiteEui: "MISSING_CURRENT_ADJUSTED_SITE_EUI",
  missingBaselineScore: "MISSING_BASELINE_SCORE",
  missingCurrentScore: "MISSING_CURRENT_SCORE",
  missingPrescriptivePointsEarned: "MISSING_PRESCRIPTIVE_POINTS_EARNED",
  missingPrescriptivePointsNeeded: "MISSING_PRESCRIPTIVE_POINTS_NEEDED",
  missingPrescriptiveRequirements: "MISSING_PRESCRIPTIVE_REQUIREMENTS",
  missingTrajectoryInputs: "MISSING_TRAJECTORY_INPUTS",
  performanceTargetMet: "PERFORMANCE_TARGET_MET",
  performanceTargetNotMet: "PERFORMANCE_TARGET_NOT_MET",
  standardTargetMet: "STANDARD_TARGET_MET",
  standardTargetNotMet: "STANDARD_TARGET_NOT_MET",
  prescriptiveRequirementsMet: "PRESCRIPTIVE_REQUIREMENTS_MET",
  prescriptiveRequirementsNotMet: "PRESCRIPTIVE_REQUIREMENTS_NOT_MET",
  trajectoryTargetMet: "TRAJECTORY_TARGET_MET",
  trajectoryTargetNotMet: "TRAJECTORY_TARGET_NOT_MET",
  alternativeComplianceCalculated: "ALTERNATIVE_COMPLIANCE_CALCULATED",
  acpAgreementRequired: "ACP_AGREEMENT_REQUIRED",
  maxPenaltyOverrideApplied: "MAX_PENALTY_OVERRIDE_APPLIED",
  noEligiblePathways: "NO_ELIGIBLE_PATHWAYS",
} as const;

export type BepsReasonCode =
  (typeof BEPS_REASON_CODES)[keyof typeof BEPS_REASON_CODES];
