ALTER TYPE "MeterType" ADD VALUE IF NOT EXISTS 'WATER_INDOOR';
ALTER TYPE "MeterType" ADD VALUE IF NOT EXISTS 'WATER_OUTDOOR';
ALTER TYPE "MeterType" ADD VALUE IF NOT EXISTS 'WATER_RECYCLED';

ALTER TYPE "EnergyUnit" ADD VALUE IF NOT EXISTS 'GAL';
ALTER TYPE "EnergyUnit" ADD VALUE IF NOT EXISTS 'KGAL';
ALTER TYPE "EnergyUnit" ADD VALUE IF NOT EXISTS 'CCF';
